package com.nobleprog.jbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SignalProcessPojo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String messageCode;
	private java.lang.String messageDesc;
	private java.lang.Long processInstanceId;
	private java.lang.String requestId;

	public SignalProcessPojo() {
	}

	public java.lang.String getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(java.lang.String messageCode) {
		this.messageCode = messageCode;
	}

	public java.lang.String getMessageDesc() {
		return this.messageDesc;
	}

	public void setMessageDesc(java.lang.String messageDesc) {
		this.messageDesc = messageDesc;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(java.lang.String requestId) {
		this.requestId = requestId;
	}

	public SignalProcessPojo(java.lang.String messageCode,
			java.lang.String messageDesc, java.lang.Long processInstanceId,
			java.lang.String requestId) {
		this.messageCode = messageCode;
		this.messageDesc = messageDesc;
		this.processInstanceId = processInstanceId;
		this.requestId = requestId;
	}

}